language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
install:
  - yarn
script:
  - yarn build
  - yarn test:coverage
# NOTE: Add deploy
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: firebase deploy -P $TRAVIS_BRANCH --token $FIREBASE_TOKEN
#   on:
#     all_branches: true
#     condition: $TRAVIS_BRANCH =~ ^develop|master$
